---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: default.yml
  roles_path: ../ansible-test-framework/ # replace with the name of your role
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_verbose: true
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04

suites:
- name: ansible