version: '2'

volumes:
  worklog:
  ckantmp:
  apachelog:

services:
  redis:
    image: redis

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fe
      - pycsw

  fgdc2iso:
    build: ./fgdc2iso
    volumes:
      - /etc/saxon-license

  fe:
    build: ./ckan
    command: /usr/sbin/apache2ctl -D FOREGROUND
    extra_hosts:
      - "catalog.data.gov:127.0.0.1"
    volumes:
      - ./configs/ckan:/etc/ckan
      - ckantmp:/var/tmp/ckan
      - apachelog:/var/log/apache2


  worker:
    build: ./ckan
    links:
      - redis
      - fe:catalog.data.gov
    volumes:
      - worklog:/var/log
      - ckantmp:/var/tmp/ckan
      - ./configs/ckan:/etc/ckan

  pycsw:
    build: ./pycsw
    command: /usr/sbin/apache2ctl -D FOREGROUND
    links:
      - fe:catalog.data.gov
    volumes:
      - ./configs/pycsw:/etc/pycsw

  gather:
    build: ./ckan
    command: ckan --plugin=ckanext-harvest harvester gather_consumer
    links:
      - redis
      - fe:catalog.data.gov
    volumes:
      - ./configs/ckan:/etc/ckan

  fetch:
    build: ./ckan
    command: ckan --plugin=ckanext-harvest harvester fetch_consumer
    links:
      - redis
      - fe:catalog.data.gov
      - fgdc2iso
    volumes:
      - ./configs/ckan:/etc/ckan
