---

basic_auth_user: user
basic_auth_hash: password

# NGinx
nginx_hostname: manage.vasili4.com
public_domain: "{{ nginx_hostname }}"

#defaultng to use testshib.org
shibboleth:
  sp_entity_id: 'https://manage.vasili4.com/shibboleth'
  idp_entity_id: 'https://idp.testshib.org/idp/shibboleth'
  authn_context_2_factor: ''
  # openssl req -x509 -newkey rsa:4096 -keyout sp-key.pem -out sp-cert.pem -days 3650 -nodes -subj "/C=US/ST=DC/L=Washington/O=Org/OU=Org/CN=*.example.com"
  sp_cert: |
    -----BEGIN CERTIFICATE-----
    MIICiDCCAjKgAwIBAgIJAPSwoC3FGl3CMA0GCSqGSIb3DQEBBQUAMGMxCzAJBgNV
    BAYTAlVTMQswCQYDVQQIEwJEQzETMBEGA1UEBxMKV2FzaGluZ3RvbjEMMAoGA1UE
    ChMDT3JnMQwwCgYDVQQLEwNPcmcxFjAUBgNVBAMUDSouZXhhbXBsZS5jb20wHhcN
    MTcwNzI4MjEyOTUwWhcNMjcwNzI2MjEyOTUwWjBjMQswCQYDVQQGEwJVUzELMAkG
    A1UECBMCREMxEzARBgNVBAcTCldhc2hpbmd0b24xDDAKBgNVBAoTA09yZzEMMAoG
    A1UECxMDT3JnMRYwFAYDVQQDFA0qLmV4YW1wbGUuY29tMFwwDQYJKoZIhvcNAQEB
    BQADSwAwSAJBAMwzErW3jAu+03/J9Xs+bHIDlGsKgVl05QAr7liAoB0bHz+AYkuh
    d+K2m1Tzmdt1TdHp0ms4DJggx7tTs3uICwECAwEAAaOByDCBxTAdBgNVHQ4EFgQU
    QoL4v2n5GLc21ThJGCNP3605rrAwgZUGA1UdIwSBjTCBioAUQoL4v2n5GLc21ThJ
    GCNP3605rrChZ6RlMGMxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJEQzETMBEGA1UE
    BxMKV2FzaGluZ3RvbjEMMAoGA1UEChMDT3JnMQwwCgYDVQQLEwNPcmcxFjAUBgNV
    BAMUDSouZXhhbXBsZS5jb22CCQD0sKAtxRpdwjAMBgNVHRMEBTADAQH/MA0GCSqG
    SIb3DQEBBQUAA0EAU6bH7HCYku49z7kJh2xTaBmoJy9jx/GP9OkU7zmxfuKHbw0Y
    sOK1cK9E10FSPhpM2ptYAK+O+cr5ChFL9BuQOA==
    -----END CERTIFICATE-----
  sp_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIBOQIBAAJBAMwzErW3jAu+03/J9Xs+bHIDlGsKgVl05QAr7liAoB0bHz+AYkuh
    d+K2m1Tzmdt1TdHp0ms4DJggx7tTs3uICwECAwEAAQJAVWXGnVh1qTPVH8xGbZRd
    phD5MQrjrZXFb5zvwPOKAqFlY9QwN3/1pNMiPbGFWWYynBSk22TI8FSsqt0EHpuc
    AQIhAPW6tuoCgtx4YXgkC+3ETZW6sPKfM5tMqevrr+sgXh/5AiEA1Lv+CW/5Rb0L
    GJKbbTisKj7oKjhstwm7CKYnJ5f9lUkCIDjgM7AsTp+7GUxWg5BQDGkoogY2RRqf
    /wCFN92jS0X5Ah80Wg8qQ2QUxXD1mx6kwk2cF98KhNg8MyjT+A+qrry5AiEAyJJx
    /dG2s0N2LDLSkw3kLI42soD/t1WHXQ7ipoX9ZbY=
    -----END RSA PRIVATE KEY-----

# web self-signed ssl stuff
# openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -nodes -subj "/C=US/ST=DC/L=Washington/O=Org/OU=Org/CN=*.example.com"
web_crt: |
  -----BEGIN CERTIFICATE-----
  MIICiDCCAjKgAwIBAgIJAO4G/U4aoEHxMA0GCSqGSIb3DQEBBQUAMGMxCzAJBgNV
  BAYTAlVTMQswCQYDVQQIEwJEQzETMBEGA1UEBxMKV2FzaGluZ3RvbjEMMAoGA1UE
  ChMDT3JnMQwwCgYDVQQLEwNPcmcxFjAUBgNVBAMUDSouZXhhbXBsZS5jb20wHhcN
  MTcwNzI4MjEyMjA1WhcNMjcwNzI2MjEyMjA1WjBjMQswCQYDVQQGEwJVUzELMAkG
  A1UECBMCREMxEzARBgNVBAcTCldhc2hpbmd0b24xDDAKBgNVBAoTA09yZzEMMAoG
  A1UECxMDT3JnMRYwFAYDVQQDFA0qLmV4YW1wbGUuY29tMFwwDQYJKoZIhvcNAQEB
  BQADSwAwSAJBAKHgernVQSrsrK2hywSnChz7iPuC+55y94oUfg7TO467Ig0goctu
  odcOmSolORXXRX28EfOB2TCS8ui3QMHSlvsCAwEAAaOByDCBxTAdBgNVHQ4EFgQU
  He/7O7VAxYCPgw/U3q0MRLt0h8cwgZUGA1UdIwSBjTCBioAUHe/7O7VAxYCPgw/U
  3q0MRLt0h8ehZ6RlMGMxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJEQzETMBEGA1UE
  BxMKV2FzaGluZ3RvbjEMMAoGA1UEChMDT3JnMQwwCgYDVQQLEwNPcmcxFjAUBgNV
  BAMUDSouZXhhbXBsZS5jb22CCQDuBv1OGqBB8TAMBgNVHRMEBTADAQH/MA0GCSqG
  SIb3DQEBBQUAA0EAk2JZ2HykPSwtXZ1qZ/fglAIPc9VyKxlsgT4FDizqcgR4jNdB
  7CE5lw7RDg4PvPHKPhP3lsXc3uOAs5IzgYtbEw==
  -----END CERTIFICATE-----

web_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIBOwIBAAJBAKHgernVQSrsrK2hywSnChz7iPuC+55y94oUfg7TO467Ig0goctu
  odcOmSolORXXRX28EfOB2TCS8ui3QMHSlvsCAwEAAQJACkUxxCSRk+WcNw/yz4LB
  k4Ep+bsft7fXmL0gGlSwjKec9gnQrC9U5jJGUYthLv+PEAZ+KKhgHBrBecy+PgIo
  kQIhAM5QNaD0DnKbcBcId/BHmZcBQY+FLvC5eJBFOIs9aDPfAiEAyNyjqeg+v3RQ
  CfY6eglseDV01XocrlDBIzB460gN4GUCIQCujkyhjnx+2SagRkj8IghALA7lOED7
  6WCpZ/esT1tPrwIgUrYgovei1x3jU6bUP6qfwwRoPvwQ0WspjP8J3AEIzc0CIQC2
  2pJCHT9YxoxZcTc6yrQgFOHed1ZGvW5v76TUPesedA==
  -----END RSA PRIVATE KEY-----
