# TrendMicro
trendmicro_policy_id_mgmt_app: "{{ vault_trendmicro_policy_id_mgmt_app }}"
trendmicro_policy_id_mgmt_web: "{{ vault_trendmicro_policy_id_mgmt_web }}"

# Max SAML
shibboleth:
  sp_entity_id: 'https://manage.data.gov'
  idp_entity_id: 'https://login.max.gov/idp/shibboleth'
  authn_context_2_factor: 'https://max.gov/icam/2015/10/securityLevels/securePlus2'
  # openssl genrsa -out sp.key 1024
  # openssl req -new -x509 -key sp.key -out sp.pem
  sp_cert: "{{ vault_saml2_sp_public_key }}"
  sp_key: "{{ vault_saml2_sp_private_pem }}"

# web self-signed ssl stuff
# openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 3650 -nodes -subj "/C=US/ST=DC/L=Washington/O=GSA/OU=Org/CN=*.mgmt-ocsit.bsp.gsa.gov"
web_crt: "{{ vault_web_crt }}"
web_key: "{{ vault_web_key }}"
