---
- name: Install EFK nginx proxy
  hosts: efk_nginx
  become: yes
  become_method: sudo
  remote_user: ubuntu

  roles:
  - { role: software/ubuntu/common, tags: ['always'] }
  - { role: monitoring/efk-nginx-saml, tags: [provision] }
  - { role: software/common/trendmicro, tags: [provision, trendmicro, prod] }
